### PR TITLE
partial match and pkmn args

### PR DESCRIPTION
**Pull request by Baviaan**
Added the digit checks to cp and lvl for consistency.

Changed the partial match penalty from .6 to .8 as nothing below 80 matches.

### CODE REVIEW

**Comment by Baviaan** [comment]
Actually I just removed the extra partial penalty completely. Because if something matches at a score of 90 it would not return the match at 80. It's making several quests not show up.

**Comment by Baviaan** [comment]
I needed a check first whether the args are long enough otherwise it crashes.

**Comment by FoglyOgly** [comment]
Will getting rid of the penalty cause more locations to be matched?

**Comment by Baviaan** [comment]
It still has the partial penalty, I only removed the additional penalty if one string is 8 times larger than the other.

Potentially more locations will be matched but I don't think in practice it will be a problem. For example if you use a 3 characters nickname it will now try to match all gyms instead of the gyms up to length 24. If the nickname is unique enough it will likely still be unique because if it was a common occurrence as substring it likely would have matched one of the gyms up to length 24 already anyway.

**Comment by FoglyOgly** [comment]
Alright. Let's give it a shot

**Pull request merged**
