### PR TITLE
Updating Level 5 Raids

### PR DESCRIPTION
**Pull request by domdigioia**
Removing Latias and Latios from Legendary Raid List

### CODE REVIEW

**Comment by wattazoum** [comment]
Hi, 

I think it's not a good idea to keep tracking the exact Lvl 5 list. That would require that you be very fast in updating the bot code. Moreover the list of active legendary is related to the country. 

What I think is that you should put the whole list of already know Raid 5 bosses, and let the users be responsible of stating the right one. 

In the documentation, you could tell that in the setup, one can adjust the list to his linking.

**Comment by FoglyOgly** [comment]
It's pretty simple to keep the list up to date using the !raid_json
command. No sense in keeping bosses around that we know don't currently
appear.

**Comment by wattazoum** [comment]
Strike my comment down. You are absolutely right. This was due to my misunderstanding of the BOT. :+1:

**Comment by nileplumb** [comment]
This is probably able to be closed now, latest boss changes also part of my merged PR.

**Pull request closed without merging**
