### PR TITLE
Team Rocket reporting

### PR DESCRIPTION
**Pull request by Baviaan**
I've added a !rocket command to support the new feature. I have it working on by test server by creating a modifiers table. It's not final, but perhaps it is good to offer some support quickly. In particular you currently cannot 'want' the reports. I've called them pokestop modifiers to catch both team rocket and lures.

I have added 6 TODO's in the code. To be precise:
2 TODO's: The 'coming' emoji doesn't do anything. (I was going to copy from wild but it doesn't do anything there.)
3 TODO's: Add functionality to want these reports.
1 TODO: Add a pretty picture to the embed.

### CODE REVIEW

**Comment by Baviaan** [comment]
I used the following to generate my table. It's a copy of my reconstruction of the wild table with 'pkmn' replaced by 'name'. 
```create table modifiers (id bigint, guild bigint, name text, reporter_id bigint, created bigint, messages text[], location text);```

**Comment by FoglyOgly** [comment]
I'd guess created needs to be double precision doesn't it? As `time.time()` is float rather than int.

**Comment by FoglyOgly** [comment]
Good start otherwise though.

**Comment by Baviaan** [comment]
Good shout. I also realised I forgot to change the location converter from POI to Pokestop.

**Pull request merged**
